### PR TITLE
Add parameter to disable `print(...)`

### PR DESCRIPTION
**Pull request by aparamon**
Fixes https://github.com/illagrenan/block-timer/issues/47

### CODE REVIEW

**Comment by aparamon** [comment]
I propose that additionally, `Timer` prints to `sys.stderr` by default.
Do you welcome such a change?

**Comment by illagrenan** [comment]
Thanks a lot! I'm sorry it takes so long. I will look at your PR this week 👍

**Comment by aparamon** [comment]
Friendly ping!

**Comment by illagrenan** [comment]
Sorry, I was a little in a hurry in the afternoon. What do you think about the latest commit? Now we have two explicit arguments: 1) should be the title printed? AND 2) file that will be passed to the print function.

**Comment by aparamon** [comment]
It's fine!
I have noticed that `redirect_stdout()` calls are now obsolete in tests as you pass the buffer directly. Let's remove the former?
What do you think if `print_file` is `sys.stderr` by default?

**Comment by illagrenan** [comment]
1. I have removed `redirect_stdout()`
2. `print_file` is `stderr` by default

Looks good? 🙂

**Comment by aparamon** [comment]
Great, thank you for your support!

**Comment by illagrenan** [comment]
Thank you for your contribution! Good job! 👍

**Pull request merged**
